env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  import/no-extraneous-dependencies: 0
  one-var: 0
  one-var-declaration-per-line: 0
